version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  fastapi:
    build: .
    command: >
      bash -c "
        echo 'Waiting for DB...' &&
        while ! nc -z db 5432; do sleep 1; done &&
        echo 'Waiting for MongoDB...' &&
        while ! nc -z mongo 27017; do sleep 1; done &&
        echo 'Waiting for Redis...' &&
        while ! nc -z redis 6379; do sleep 1; done &&
        echo 'Waiting for RabbitMQ...' &&
        while ! nc -z rabbitmq 5672; do sleep 1; done &&
        echo 'All services ready, starting app' &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - mongo
      - redis
      - rabbitmq

volumes:
  postgres_data:
  mongo_data:
